'use strict';
const $=sel=>document.querySelector(sel);
const state={catalog:{recipes:[]},graph:null,drag:null};
const nodeMeta={source:['01','原图','SOURCE MASTER'],look:['02','风格 A','Photo Refiner Look'],'creative-effect':['03','效果 B','Starryear Creative'],approval:['04','确认','Approval Gate'],recovery:['05','高分恢复','Detail Recovery'],delivery:['06','交付','Delivery']};
const defaultConfig={sourceCount:1,preset:'natural-cinematic',styleStrength:45,creativeRecipe:'none',creativeAssemblyMode:'direct-effect',creativeFromBase:false,deliveryMode:'preview-first',resolution:'source-width',outputFormat:'jpg',detail:{mode:'adaptive',generationBudget:'balanced',patchScope:'head-and-face',strength:60}};

async function boot(){try{state.catalog=await fetch('../skill/references/starryear/catalog.json').then(r=>{if(!r.ok)throw new Error('catalog');return r.json()})}catch{state.catalog={recipes:[]}}reset(defaultConfig);bindToolbar();window.addEventListener('resize',drawEdges)}
function recipe(id){return state.catalog.recipes.find(x=>x.id===id)}
function node(id,type,enabled,config,x,y){return{id,type,enabled,config,position:{x,y}}}
function configToGraph(c){
  const count=Math.max(1,Number(c.sourceCount||1)),rid=c.creativeRecipe||'none',creative=rid!=='none',assembly=c.creativeAssemblyMode||'direct-effect',fromBase=assembly==='original-assembly'?false:Boolean(c.creativeFromBase);
  const renderMode=!creative||fromBase?'look-master':'direction-only',detail=c.detail||{},dmode=detail.mode||'adaptive';
  let recovery=!creative?(dmode==='base-only'?'disabled':'normal'):(assembly==='original-assembly'||count>1||dmode==='base-only'?'disabled':'creative-safe');
  const nodes=[node('source','source',true,{sourceCount:count},40,180),node('look_a','look',true,{preset:c.preset||'natural-cinematic',styleStrength:Number(c.styleStrength??45),renderMode},260,180)];
  if(creative){const r=recipe(rid);nodes.push(node('effect_b','creative-effect',true,{recipeId:rid,mode:assembly,sourceCommit:r?.sourceCommit||'',upstreamBinding:renderMode==='look-master'?'look-master':'direction-only'},480,180))}
  nodes.push(node('approval','approval',true,{deliveryMode:c.deliveryMode||'preview-first'},creative?700:480,180));
  nodes.push(node('recovery','recovery',recovery!=='disabled',{mode:recovery,detailMode:dmode,generationBudget:detail.generationBudget||'balanced',patchScope:detail.patchScope||'head-and-face',strength:Number(detail.strength??60)},creative?920:700,180));
  nodes.push(node('delivery','delivery',true,{resolution:c.resolution||'source-width',outputFormat:c.outputFormat||'jpg'},creative?1140:920,180));
  return makeGraph(nodes,'node-canvas');
}
function makeGraph(nodes,createdFrom){const ids=nodes.filter(n=>n.enabled).map(n=>n.id);return{version:1,graphId:`node-canvas-${Date.now()}`,createdFrom,nodes,edges:ids.slice(0,-1).map((id,i)=>({from:id,to:ids[i+1],kind:'flow'})),metadata:{ui:'node-canvas-alpha'}}}
function reset(config){state.graph=configToGraph(structuredClone(config));render()}
function render(){const host=$('#nodes');host.innerHTML='';state.graph.nodes.forEach((n,i)=>host.appendChild(renderNode(n,i)));refreshGraph();requestAnimationFrame(drawEdges)}
function renderNode(n,index){
  const el=$('#nodeTemplate').content.firstElementChild.cloneNode(true);el.dataset.id=n.id;el.classList.toggle('disabled',!n.enabled);el.style.left=`${n.position.x}px`;el.style.top=`${n.position.y}px`;
  const meta=nodeMeta[n.type];el.querySelector('.node-index').textContent=meta[0];el.querySelector('.node-title b').textContent=meta[1];el.querySelector('.node-title small').textContent=meta[2];
  el.insertAdjacentHTML('afterbegin','<span class="port in"></span>');el.insertAdjacentHTML('beforeend','<span class="port out"></span>');el.querySelector('.node-body').appendChild(fieldsFor(n));bindDrag(el,n);return el;
}
function fieldsFor(n){const f=document.createElement('div'),c=n.config;
  if(n.type==='source')f.innerHTML=fieldNum('原图数量','sourceCount',c.sourceCount,1,5)+`<div class="hint">决定 Starryear recipe 的可用范围。</div>`;
  if(n.type==='look')f.innerHTML=fieldText('预设','preset',c.preset)+fieldRange('强度','styleStrength',c.styleStrength)+fieldSelect('执行语义','renderMode',c.renderMode,[['direction-only','只提供风格方向'],['look-master','先生成 LOOK_A']]);
  if(n.type==='creative-effect'){const opts=state.catalog.recipes.map(r=>[r.id,`${r.number} · ${r.titleZh}`]);f.innerHTML=fieldSelect('Starryear','recipeId',c.recipeId,opts)+fieldSelect('输出模式','mode',c.mode,[['direct-effect','只应用创意效果'],['original-assembly','忠于原版结构']])+`<div class="hint recipe-meta"></div>`}
  if(n.type==='approval')f.innerHTML=fieldSelect('确认方式','deliveryMode',c.deliveryMode,[['preview-first','先看效果图'],['one-click','一次成片']]);
  if(n.type==='recovery')f.innerHTML=`<div class="field"><label>策略 <span>${c.mode}</span></label><div class="hint">由图结构自动推导：普通 / creative-safe / disabled。</div></div>`+fieldSelect('生成预算','generationBudget',c.generationBudget,[['fast','快速'],['balanced','平衡'],['max','最大']]);
  if(n.type==='delivery')f.innerHTML=fieldSelect('尺寸','resolution',c.resolution,[['source-width','原图尺寸'],['4k','4K'],['preview','预览']])+fieldSelect('格式','outputFormat',c.outputFormat,[['jpg','JPG'],['png','PNG'],['both','两种']]);
  f.querySelectorAll('[data-key]').forEach(input=>input.addEventListener('input',()=>changeNode(n,input.dataset.key,input.type==='number'?Number(input.value):input.value)));if(n.type==='creative-effect')updateRecipeMeta(f,n);return f;
}
function fieldText(label,key,value){return`<div class="field"><label>${label}</label><input type="text" data-key="${key}" value="${escapeHtml(value)}"></div>`}
function fieldNum(label,key,value,min,max){return`<div class="field"><label>${label}</label><input type="number" data-key="${key}" min="${min}" max="${max}" value="${value}"></div>`}
function fieldRange(label,key,value){return`<div class="field"><label>${label}<span>${value}</span></label><input type="range" data-key="${key}" min="0" max="100" value="${value}"></div>`}
function fieldSelect(label,key,value,opts){return`<div class="field"><label>${label}</label><select data-key="${key}">${opts.map(([v,l])=>`<option value="${escapeHtml(v)}"${v===value?' selected':''}>${escapeHtml(l)}</option>`).join('')}</select></div>`}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function changeNode(n,key,value){n.config[key]=value;if(n.type==='source'||n.type==='look'||n.type==='creative-effect')rederive();else refreshGraph()}
function rederive(){const s=get('source'),l=get('look'),b=get('creative-effect'),r=getAny('recovery');const count=Number(s.config.sourceCount||1);if(b){if(b.config.mode==='original-assembly')l.config.renderMode='direction-only';b.config.upstreamBinding=l.config.renderMode==='look-master'?'look-master':'direction-only';const rec=recipe(b.config.recipeId);b.config.sourceCommit=rec?.sourceCommit||''}if(r){r.enabled=true;if(!b)r.config.mode='normal';else if(b.config.mode==='original-assembly'||count>1){r.config.mode='disabled';r.enabled=false}else r.config.mode='creative-safe'}rebuildEdges();render()}
function rebuildEdges(){const ids=state.graph.nodes.filter(n=>n.enabled).map(n=>n.id);state.graph.edges=ids.slice(0,-1).map((id,i)=>({from:id,to:ids[i+1],kind:'flow'}))}
function get(type){return state.graph.nodes.find(n=>n.type===type&&n.enabled)}function getAny(type){return state.graph.nodes.find(n=>n.type===type)}
function validate(){try{const order=state.graph.nodes.filter(n=>n.enabled).map(n=>n.type),expected=['source','look',...(get('creative-effect')?['creative-effect']:[]),'approval',...(get('recovery')?['recovery']:[]),'delivery'];if(order.join('|')!==expected.join('|'))throw new Error('节点顺序非法');const s=get('source');if(!s||Number(s.config.sourceCount)<1)throw new Error('至少需要一张原图');const b=get('creative-effect');if(b){const rr=recipe(b.config.recipeId);if(!rr)throw new Error('找不到 Starryear recipe');const c=Number(s.config.sourceCount);if(c<rr.sourceCount.min||c>rr.sourceCount.max)throw new Error(`${rr.number} 需要 ${rr.sourceCount.min===rr.sourceCount.max?rr.sourceCount.min:`${rr.sourceCount.min}–${rr.sourceCount.max}`} 张原图`);if(b.config.mode==='original-assembly'&&get('look').config.renderMode==='look-master')throw new Error('原版拼接不能消费 LOOK_A 主图')}return{ok:true}}catch(e){return{ok:false,error:e.message}}}
function compile(){const v=validate();if(!v.ok)return{error:v.error,steps:[]};const look=get('look'),b=get('creative-effect'),a=get('approval'),rec=get('recovery'),d=get('delivery'),steps=[['准备原图','prepare-source',false]];if(look.config.renderMode==='look-master')steps.push(['生成 LOOK_A','render-look',Boolean(b&&a.config.deliveryMode==='preview-first')]);else steps.push(['解析 A 风格方向','resolve-look-direction',false]);if(b)steps.push([b.config.mode==='original-assembly'?'执行 Starryear 原版结构':'生成 B 创意效果','render-creative-effect',a.config.deliveryMode==='preview-first']);steps.push(['确认 LOOK MASTER','approval-gate',false]);if(rec)steps.push([rec.config.mode==='creative-safe'?'创意安全高分恢复':'常规高分恢复','detail-recovery',false]);steps.push(['交付成片','delivery',false]);return{steps}}
function refreshGraph(){const result=validate(),badge=$('#validationBadge');badge.textContent=result.ok?'Graph OK':result.error;badge.className=`badge ${result.ok?'ok':'bad'}`;const c=compile();$('#planLine').textContent=c.error?'无法编译':c.steps.map(x=>x[0]).join(' → ');const list=$('#planSteps');list.innerHTML='';c.steps.forEach((s,i)=>{const li=document.createElement('li');li.className=s[2]?'wait':'';li.innerHTML=`<strong>${String(i+1).padStart(2,'0')}</strong>${escapeHtml(s[0])}${s[2]?' · 待确认':''}`;list.appendChild(li)});$('#planHash').textContent=simpleHash(JSON.stringify(state.graph));drawEdges()}
function updateRecipeMeta(root,n){const r=recipe(n.config.recipeId),el=root.querySelector('.recipe-meta');if(!r){el.textContent='未找到 recipe';return}el.textContent=`${r.sourceCount.min===r.sourceCount.max?r.sourceCount.min:`${r.sourceCount.min}–${r.sourceCount.max}`} 张 · 原版 ${r.output.layoutZh} · ${r.sourceCommit.slice(0,7)}`}
function bindDrag(el,n){const head=el.querySelector('.node-head');head.addEventListener('pointerdown',e=>{if(e.button!==0)return;const canvas=$('#canvas').getBoundingClientRect();state.drag={n,el,dx:e.clientX-canvas.left+$('#canvas').scrollLeft-n.position.x,dy:e.clientY-canvas.top+$('#canvas').scrollTop-n.position.y};el.classList.add('dragging');head.setPointerCapture(e.pointerId)});head.addEventListener('pointermove',e=>{if(!state.drag||state.drag.n!==n)return;const canvas=$('#canvas').getBoundingClientRect();n.position.x=Math.max(10,e.clientX-canvas.left+$('#canvas').scrollLeft-state.drag.dx);n.position.y=Math.max(10,e.clientY-canvas.top+$('#canvas').scrollTop-state.drag.dy);el.style.left=`${n.position.x}px`;el.style.top=`${n.position.y}px`;drawEdges()});head.addEventListener('pointerup',()=>{if(state.drag?.n===n){el.classList.remove('dragging');state.drag=null}})}
function drawEdges(){const svg=$('#edges'),canvas=$('#canvas');if(!svg||!state.graph)return;svg.innerHTML='';const rect=canvas.getBoundingClientRect();for(const edge of state.graph.edges){const a=document.querySelector(`[data-id="${edge.from}"] .port.out`),b=document.querySelector(`[data-id="${edge.to}"] .port.in`);if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.left+ar.width/2-rect.left+canvas.scrollLeft,y1=ar.top+ar.height/2-rect.top+canvas.scrollTop,x2=br.left+br.width/2-rect.left+canvas.scrollLeft,y2=br.top+br.height/2-rect.top+canvas.scrollTop,m=Math.max(45,(x2-x1)*.48),d=`M ${x1} ${y1} C ${x1+m} ${y1}, ${x2-m} ${y2}, ${x2} ${y2}`;svg.insertAdjacentHTML('beforeend',`<path class="edge-glow" d="${d}"/><path class="edge" d="${d}"/>`)}}
function bindToolbar(){$('#resetBtn').onclick=()=>reset(defaultConfig);$('#validateBtn').onclick=()=>{const r=validate();alert(r.ok?'Graph 校验通过':r.error)};$('#exportBtn').onclick=exportGraph;$('#importConfig').onchange=importConfig}
async function importConfig(e){const file=e.target.files?.[0];if(!file)return;try{const c=JSON.parse(await file.text());reset({...defaultConfig,...c,detail:{...defaultConfig.detail,...(c.detail||{})}})}catch(err){alert(`导入失败：${err.message}`)}finally{e.target.value=''}}
function exportGraph(){const blob=new Blob([JSON.stringify(state.graph,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='photo-refiner-graph.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function simpleHash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return`ui-${(h>>>0).toString(16).padStart(8,'0')}`}
boot();
